# Generated by Django 6.0.3 on 2026-03-18 15:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_date", models.DateField(db_index=True)),
                (
                    "planned_duration_min",
                    models.PositiveIntegerField(
                        default=25,
                        validators=[django.core.validators.MaxValueValidator(600)],
                    ),
                ),
                ("actual_duration_min", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("IN_PROGRESS", "Em andamento"),
                            ("COMPLETED", "Concluída"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="PomodoroSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("focus_duration_min", models.PositiveIntegerField(default=25)),
                ("break_duration_min", models.PositiveIntegerField(default=5)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("was_completed", models.BooleanField(default=False)),
                (
                    "study_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pomodoros",
                        to="core.studysession",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "color_hex",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator("^#[0-9A-Fa-f]{6}$")
                        ],
                    ),
                ),
                ("icon", models.CharField(default="📚", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="studysession",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="core.subject",
            ),
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["user", "scheduled_date"], name="core_studys_user_id_2c835d_idx"
            ),
        ),
    ]
